import { OPENROUTER_MODEL } from "../../config/constants.js";

export const generateAutomationContent = async ({ mode, templateBody, context }) => {
  const contextSummary = JSON.stringify(context || {}).slice(0, 1000);
  if (mode === "AI Generate (Auto Reply)") {
    return `Auto reply generated by ${OPENROUTER_MODEL}:\n\n${templateBody}\n\nContext: ${contextSummary}`;
  }

  return `Draft generated by ${OPENROUTER_MODEL}:\n\n${templateBody}\n\nContext: ${contextSummary}`;
};
